### ISSUE TITLE
Can you please add this patch to revanced_patches?

### ISSUE THREAD

**Issue by ycngmn** [pgaskin/lithiumpatch#1]
Hello, loved the features of your patch but unfortunetly I can't use it as I don't have acces to computers. 

Can you please intergeate this patch in revanced patches. It allows to patch apks through 'Revanced Manager' from android phones. You can check out the repo : [revanced_patches](https://github.com/revanced/revanced-patches) 

Peace 🕊️ .

**Comment by pgaskin** [comment]
I don't plan to add this to revanced myself, but after taking a quick look at revanced, it should be possible to do so. The hardest one would be the custom fonts.

It should be possible to run this directly on an Android device using Termux, though.
