### ISSUE TITLE
Font cannot be choose if an EPUB is in other language other than english

### ISSUE THREAD

**Issue by gozilla-paradise** [pgaskin/lithiumpatch#3]
![image](https://github.com/pgaskin/lithiumpatch/assets/8213866/d703923a-162b-4fe6-a8fe-ba5523b61399)

When dc:language is set to other language (eg. th), the font dialog didn't show font list except Original font.

**Comment by pgaskin** [comment]
Yes, Lithium filters fonts based on their glyphs. It doesn't include Thai iirc, but regardless, I don't think any of the fonts included do.

I can add support for filtering for Thai glyphs, then you'll be able to build a custom APK with your own fonts.

**Comment by pgaskin** [comment]
@gozilla-paradise I've added support for Thai fonts, and also added two of the most popular ones from Google Fonts.

**Comment by pgaskin** [comment]
@gozilla-paradise I've also added an option to disable page turn animations.
